image: harbor.yy.com/front_end/node:12.7.0

stages:
  - build_dev
  - build
  - release

before_script:
  - yarn config set registry https://npm-registry.yy.com

build_dev:
  stage: build
  tags:
    - webfe
  only:
    - test
  artifacts:
    expire_in: 1 week
    paths:
    - dist/
    - package.json
  script:
    - cp -r /data/lfx-vue-pre-installed/node_modules ./node_modules
    - yarn install
    - npm run build:dev

build:
  stage: build
  tags:
    - webfe
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
    - dist/
    - package.json
  script:
    - cp -r /data/lfx-vue-pre-installed/node_modules ./node_modules
    - yarn install
    - npm run build

.release:
  stage: release
  tags:
    - webfe
  script:
    - yarn global add @yy/rv-cli
    - find ./dist/js/ -name '*.map' -type f -print -exec rm -rf {} \;
    - rv dist

release_test:
  extends: .release
  only:
    - test

release_prod:
  extends: .release
  when: manual
  only:
    - master
